
format = """
$custom
$character
"""

# -------- DIRECTORY TREE (ONLY WHEN NOT HOME) --------
[custom.dir_tree]
when = '[[ "$PWD" != "$HOME" ]]'
command = 'echo "┌─  ${PWD/#$HOME/~}\n│"'
style = "bold cyan"

# -------- CHARACTER (SMART) --------
[character]
success_symbol = "[󰣇 ❯](bold blue)"
error_symbol   = "[󰣇 ❯](bold red)"

